apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-retail-store-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GuyArnan/retail-app-argoCD-config # Your GitOps repo
    targetRevision: HEAD
    path: argocd-config/applications # ⬅️ Monitors the directory containing all child app manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Deploys the Application resources into the ArgoCD namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
