apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-cart
  namespace: argocd # All ArgoCD Application definitions should live in the argocd namespace
spec:
  project: default
  source:
    repoURL: https://github.com/GuyArnan/retail-app-argoCD-config # Your GitOps repo
    targetRevision: HEAD
    path: charts/cart # ⬅️ Path to the Catalog service Helm chart
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-prod # Deploy to your production namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
